apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: nginx-active
      previewService: nginx-preview
      autoPromotionEnabled: false  # 수동 승인을 위해 false
      previewReplicaCount: 2
---

  # 액티브 서비스 (사용자 트래픽이 전달되는 곳)
  apiVersion: v1
  kind: Service
  metadata:
    name: nginx-active
  spec:
    selector:
      app: nginx
    ports:
    - port: 80
      targetPort: 80

---

  # 프리뷰 서비스 (새 버전만 연결됨)
  apiVersion: v1
  kind: Service
  metadata:
    name: nginx-preview
  spec:
    selector:
      app: nginx
    ports:
    - port: 80
      targetPort: 80
